language: cpp
compiler: gcc
dist: Xenial

cache: 
- directories:
  - $HOME/.cache

script: 
  - REPO_HOME=`pwd`
  - pwd
  - cd $REPO_HOME && bash install_dependencies.sh
  - cd $REPO_HOME && bash build.sh

notifications:
  email:
    - bnuzpk@gmail.com
