language: cpp
compiler: gcc
dist: Xenial

cache: 
- directories:
  - $HOME/.cache

install: 
  - mkdir -p $HOME/.cache && cd $HOME/.cache
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-cpp-3.7.1.tar.gz
  - cd protobuf-3.7.1
  - ./configure
  - make -j $(nproc)
  - make check
  - sudo make install
  - sudo ldconfig

script: 
  - cd $HOME && ./build.sh

notifications:
  email:
    - bnuzpk@gmail.com
