language: cpp
compiler: gcc
dist: Xenial

cache: 
- directories:
  - $HOME/.cache

script: 
  - cd $HOME && bash install_dependencies.sh
  - cd $HOME && bash build.sh

notifications:
  email:
    - bnuzpk@gmail.com
